### GET all compliance documents
GET http://localhost:8080/api/compliance-document

### CREATE new Compliance doc
POST http://localhost:8080/api/compliance-document
Content-Type: application/json

{

  "documentName": "ColaMente & Co",
  "documentUploadDate": "2026-06-05",
  "documentStatus": "PENDING",
  "documentType": "BUSINESS_CERTIFICATE",
  "regulations": []
}

### CREATE new Compliance doc with regulation
POST http://localhost:8080/api/compliance-document
Content-Type: application/json

{

  "documentName": "SH ID",
  "documentUploadDate": "2026-06-05",
  "documentStatus": "APPROVED",
  "documentType": "ID",
  "regulations": [
    {
      "description": "Sellers has tu work with some Labs to get their products tested",
      "marketplace": "FR",
      "title": "Children's Toys FR"
    }
  ]
}

### GET Compliance doc by status
GET http://localhost:8080/api/compliance-document/status/APPROVED

### GET COmpliance doc by ID
GET http://localhost:8080/api/compliance-document/1

### UPDATE compliance doc by ID
PUT http://localhost:8080/api/compliance-document/1
Content-Type: application/json

{

"documentName": "VAT form",
"documentUploadDate": "2026-06-05",
"documentStatus": "APPROVED",
"documentType": "VAT",
"regulations": [
  {
    "description": "Sellers has tu work with some Labs to get their products tested",
    "marketplace": "FR",
    "title": "Children's Toys FR"
  }
]
}