### GET ALL USERS
GET http://localhost:8080/api/users

### GET USERS BY ID
GET http://localhost:8080/api/users/5

### CREATE NEW USER
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "Test usernameee",
  "password": "ash+4cWEYK",
  "complianceStatus": "NON_COMPLIANT",
  "roles": [
    {
      "id": 1,
      "roleName": "Seller"
    }
  ]
}

### CREATE NEW USER WITH USERPROFILE INFO (not working)
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "Test username2",
  "password": "ash+45672kjgxcWEYK",
  "complianceStatus": "NON_COMPLIANT",
  "roles": [
    {
      "id": 1,
      "roleName": "Seller"
    }
  ],
  "userProfile": [
    {
      "firstName": "user",
      "lastName": "Profile",
      "email": "test@email.com"
    }
  ]
}


### UPDATE USER
PUT http://localhost:8080/api/users/6
Content-Type: application/json

{
"username": "User6"
}

### DELETE USER (check this again)
DELETE http://localhost:8080/api/users/6