package com.example.compliancehubapi.enums;

public enum DocumentTypeEnum {
    NATIONAL_ID,
    ID,
    PASSPORT,
    DRIVERS_LICENSE,
    PROOF_OF_RESIDENCE,
    BUSINESS_CERTIFICATE,
    TRADEMARK_CERTIFICATE,
    TAX_IDENTIFICATION_NUMBER,
    BANK_ACCOUNT_STATEMENT,
    FINANCIAL_STATEMENT,
    VAT_EXEMPTION_CERTIFICATE,
    VAT,
    PRODUCTION_LICENSE,
    PRODUCT_SAFETY_CERTIFICATE,
    CE_MARKING_CERTIFICATE,
    INSURANCE_CERTIFICATE,
    IMPORTED_CERTIFICATE,
    EXPORTED_CERTIFICATE,
    GDPR_CERTIFICATE,
    DATA_PROTECTION_CERTIFICATE,
    OTHER;

}
